apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: default
#  labels:
#    name: coredns-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.5
  ports:
    - port: 53
      protocol: TCP
  selector:
    app: coredns-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.5
  ports:
    - port: 53
      protocol: UDP
  selector:
    app: coredns-udp