apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: jane
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: ken
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io