apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: prometheus
  name: pod-reader
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - pods

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
  namespace: prometheus
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader